- name: Update the haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0664
    owner: root
    group: haproxy

- name: Restart haproxy
  service: name=haproxy state=restarted
